diff --git a/Makefile.in b/Makefile.in
index fa12b04..abaaac5 100644
--- a/Makefile.in
+++ b/Makefile.in
@@ -10,7 +10,8 @@ DIRS	= src/util src/global src/dns src/tls src/xsasl src/master src/milter \
 	src/postsuper src/qmqpd src/spawn src/flush src/verify \
 	src/virtual src/proxymap src/anvil src/scache src/discard src/tlsmgr \
 	src/postmulti src/postscreen src/dnsblog src/tlsproxy \
-	src/posttls-finger src/postlogd
+	src/posttls-finger src/postlogd \
+	src/mjpostdb
 MANDIRS	= proto man html
 LIBEXEC	= libexec/post-install libexec/postfix-script libexec/postfix-wrapper \
 	libexec/postmulti-script libexec/postfix-tls-script
